#!/bin/sh

echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "👋 Thank you for installing"
echo "💪 I work very hard to make good, free and open source tweaks for everyone"
echo "💰 If you want to support, you can buy me a coffee at www.paypal.me/haoict"
echo "💖 Hope you enjoy the tweak"
echo "👨‍💻 Developer: Hao Nguyen"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

FILEPATH=/System/Library/Audio/UISounds
# FILES=( "begin_record.caf" "end_record.caf" "photoShutter.caf" )
FILES0=begin_record.caf
FILES1=end_record.caf
FILES2=photoShutter.caf

if test -f "$FILEPATH/$FILES0"; then
  mv $FILEPATH/$FILES0 $FILEPATH/$FILES0.bak
else
  echo "$FILEPATH/$FILES0 does not exist. Nothing to do"
fi

if test -f "$FILEPATH/$FILES1"; then
  mv $FILEPATH/$FILES1 $FILEPATH/$FILES1.bak
else
  echo "$FILEPATH/$FILES1 does not exist. Nothing to do"
fi

if test -f "$FILEPATH/$FILES2"; then
  mv $FILEPATH/$FILES2 $FILEPATH/$FILES2.bak
else
  echo "$FILEPATH/$FILES2 does not exist. Nothing to do"
fi

